server:
  port: 8803

spring:
  application:
    name: cloud-stream-client
  cloud:
    stream:
      binders:   #绑定rabbitmq服务信息
        defaultRabbit:  #定义名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:  # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:     #服务的整合处理
        input:     #这个名字是一个通道的名称
          destination: studyExchange
          content-type: application/json  #消息类型
          binder: defaultRabbit   #具体设置
          group: atguiguA




eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔
    lease-expiration-duration-in-seconds: 5 #最长等到时间
    instance-id: send-8802.com  #在信息列表时显示主机名称
    perfer-ip-address: true  #访问的路径变为IP地址


management:
  endpoints:
    web:
      exposure:
        include: "*"


