server:
  port: 9004

spring:
  application:
    name: cloud-alibaba
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.250.108:1111



management:
  endpoints:
    web:
      exposure:
        include: "*"


