server:
  port: 8005

spring:
  application:
    name: cloud-payment-service

  cloud:
    consul:
      host: localhost
      port: 8500

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.28.228.208:3306/cloud
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.entities


